# Generated by Django 3.0.4 on 2020-03-27 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='body',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='title',
            new_name='mod',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='author',
            new_name='name',
        ),
    ]
